### ISSUE TITLE
homework1 調整事項

### ISSUE THREAD

**Issue by hatelove** [bng86/TDD-HW1#1]
單看測試案例，看不出來需求中的 context, 例如 Product 有哪些 property?
測試類別名稱也建議修改一下。

我們要表達出來的需求是：
1. 有一群 product, 當我想3筆一組，並取得每一組的Cost總和時，我期望結果應該是 {6, 15, 24, 21}
2. 有一群 product, 當我想4筆一組，並取得每一組的Revenue總和時，我期望結果應該是 {50, 66, 60}

**Comment by bng86** [comment]
感謝 91 哥的建議，
已補上測試案例的 context，並將專案、類別及變數命名的更精確一些。
已 push 上新的版本

**Comment by hatelove** [comment]
請再依據 comment 調整。

https://github.com/bng86/TDD-HW1/commit/9d4582fd3865af02ef3d03313aade347ceca0cf1

**Comment by bng86** [comment]
依據https://github.com/bng86/TDD-HW1/commit/9d4582fd3865af02ef3d03313aade347ceca0cf1 
調整測試案例及實作程式碼，將測試案例內商業邏輯移出，並修改 api 簽章
已調整完畢

**Comment by hatelove** [comment]
great!
